import {
    ArrowRight,
    Check,
    ChevronDown,
    Copy,
    Edit,
    EllipsisIcon as EllipsisHorizontal,
    ExternalLink,
    File,
    Github,
    Loader2,
    LogOut,
    Mail,
    MessageSquare,
    Plus,
    MoreHorizontal,
    RotateCw,
    Search,
    Settings,
    Trash,
    User,
    UserPlus,
    CalendarHeart,
    ChromeIcon as Google,
} from "lucide-react"

export const Icons = {
    arrowRight: ArrowRight,
    check: Check,
    chevronDown: ChevronDown,
    close: "X",
    copy: Copy,
    edit: Edit,
    ellipsisHorizontal: EllipsisHorizontal,
    externalLink: ExternalLink,
    file: File,
    github: Github,
    google: Google,
    loader2: Loader2,
    logOut: LogOut,
    mail: Mail,
    messageSquare: MessageSquare,
    moreHorizontal: MoreHorizontal,
    plus: Plus,
    rotateCw: RotateCw,
    search: Search,
    settings: Settings,
    spinner: Loader2,
    trash: Trash,
    user: User,
    userPlus: UserPlus,
    calendarHeart: CalendarHeart,
}

